import type { Metadata } from "next";
import { Inter,Nunito } from "next/font/google";
import "./globals.css";

const font = Nunito({weight:"800",subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pet Sample",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        />
      </head>
      <body className={font.className}>{children}</body>
    </html>
  );
}
